defaultContentLanguage: en
languages:
  en:
    weight: 1
    baseURL: http://open-elements.com/
    languageCode: en-us
    languageName: "English"
    description: "Open Elements Englisch description"
  de:
    weight: 2
    baseURL: http://open-elements.de/
    languageCode: de
    languageName: "Deutsch"
    description: "Open Elements deutsche Beschreibung"

title: Open Elements
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
